### ISSUE TITLE
Potential duplicate methods, BB vs bb

### ISSUE THREAD

**Issue by EngineeringAsArt** [victorgau/CandleStick#1]
Why is the bollinger band method repeated in twice: BB and bb? I understand that bb uses explicit variable declaration but I don't see any other difference. Are there any?

**Comment by victorgau** [comment]
Yes, they are the same.  I guess I copied the code from the Internet, and did not notice that I have got one implementation of Bollinger Bands in the code. 

The code is originally from https://github.com/matplotlib/mpl_finance.  It has been modified and moved to https://github.com/victorgau/kchart, so that I can easily use it with pandas.

Thanks!
